---
- name: Create Django server
  hosts: terraform-ansible
  tasks:
    # - name: Create index file
    #   copy:
    #     dest: /home/ubuntu/index.html
    #     content: <h1>Made by Terraform-Ansible 5</h1>
    # - name: Create static file server
    #   shell: "nohup busybox httpd -f -p 8080 &"
    - name: Install Python3 and VirtualEnv
      ansible.builtin.apt:
        pkg:
          - python3
          - virtualenv
        update-cache: true
      become: true

    - name: Install Django and Django Rest via pip
      ansible.builtin.pip:
        virtualenv: /home/ubuntu/virtual/venv
        name:
          - django
          - djangorestframework

    - name: Check that the django server exists
      ansible.builtin.stat:
        path: /home/ubuntu/virtual/manage.py
      register: djangoserver

    - name: Init server, if it doesn't exist already
      ansible.builtin.shell: ". /home/ubuntu/virtual/venv/bin/activate ; django-admin startproject setup /home/ubuntu/virtual"
      when: not djangoserver.stat.exists
      changed_when: true

    - name: Setup django hosts settings
      ansible.builtin.lineinfile:
        path: /home/ubuntu/virtual/setup/settings.py
        regexp: "ALLOWED_HOSTS = \\[.*\\]"
        line: 'ALLOWED_HOSTS = ["{{ ansible_host }}"]'
        backrefs: true

    - name: Start server
      ansible.builtin.shell: ". /home/ubuntu/virtual/venv/bin/activate ; nohup python /home/ubuntu/virtual/manage.py runserver 0.0.0.0:8000 &"
      changed_when: true
