- name: Install MySQL
  ansible.builtin.apt:
    pkg:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: true
  become: true

- name: Setup WordPress MySQL database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  become: true

- name: Create WordPress user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
    state: present
    column_case_sensitive: false
    login_unix_socket: /run/mysqld/mysqld.sock
    host: "{{ item }}"
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "{{ hostvars['wordpress']['ansible_host'] }}"
  become: true

- name: Update MySQL config
  ansible.builtin.replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  become: true
  notify: Restart MySQL
